version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo Installing frontend packages
      - cd frontend
      - npm install

      - echo Installing backend packages
      - cd ../backend
      - npm install

  build:
    commands:
      - echo Building React app
      - cd ../frontend
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist